# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g1', '0002_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g1.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=200, unique=True, verbose_name='nome'),
        ),
    ]
