# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g1', '0004_auto_20170327_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='realizador',
        ),
    ]
