# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g1', '0005_remove_evento_realizador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
