# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('g1', '0010_delete_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('eventoPrincipal', models.CharField(max_length=200, verbose_name='evento principal')),
                ('sigla', models.CharField(max_length=200, verbose_name='sigla')),
                ('dataEHoradeInicio', models.DateField(default=django.utils.timezone.now, verbose_name='data e hora inicio')),
                ('palavrasChave', models.TextField(blank=True, null=True, verbose_name='palavras chaves')),
                ('logotipo', models.TextField(blank=True, null=True, verbose_name='logotipo')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='nome')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
            ],
        ),
    ]
