# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g1', '0012_evento_realizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cep',
            field=models.TextField(blank=True, null=True, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.TextField(blank=True, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='evento',
            name='uf',
            field=models.TextField(blank=True, null=True, verbose_name='uf'),
        ),
    ]
