# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g1', '0013_auto_20170327_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.TextField(blank=True, null=True, verbose_name='issn')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='issn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='g1.EventoCientifico'),
        ),
    ]
